# Generated by Django 5.2.6 on 2026-02-27 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_organizationmember_organization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('vat_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('pit_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'industries',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='OrganizationIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_industries', to='users.industry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_industries', to='users.organization')),
            ],
            options={
                'db_table': 'organization_industries',
                'unique_together': {('organization', 'industry')},
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='industries',
            field=models.ManyToManyField(related_name='organizations', through='users.OrganizationIndustry', to='users.industry'),
        ),
    ]
