# Generated by Django 5.2.6 on 2026-03-18 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_industry_organization_address_organizationindustry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='is_public_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
