# Generated by Django 5.2.6 on 2026-03-30 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_module_is_public_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ kích hoạt'), ('active', 'Đang hoạt động'), ('suspended', 'Tạm khóa')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='organization',
            name='legal_form',
            field=models.CharField(choices=[('HKD', 'Hộ kinh doanh'), ('ENTERPRISE', 'Doanh nghiệp')], max_length=20),
        ),
    ]
