# Generated by Django 5.2.6 on 2026-03-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_paymenttransaction_organization_activated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='expires_at',
        ),
        migrations.AddField(
            model_name='user',
            name='is_onboarded',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='upload/%Y/%m', verbose_name='Ảnh đại diện'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Đăng nhập gần nhất'),
        ),
    ]
