# Generated by Django 5.2.6 on 2026-04-21 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshell', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidearticle',
            name='type',
            field=models.CharField(choices=[('landing', 'Landing Video'), ('about', 'About'), ('faq', 'FAQ')], default='landing', max_length=20),
        ),
    ]
