# Generated by Django 5.2.6 on 2026-04-21 03:59

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshell', '0002_guidearticle_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guidearticle',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='guidearticle',
            name='type',
        ),
        migrations.AddField(
            model_name='guidearticle',
            name='guide_type',
            field=models.CharField(choices=[('video', 'Video Guide'), ('article', 'Article Guide')], db_index=True, default='video', max_length=20),
        ),
        migrations.AddField(
            model_name='guidearticle',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guidearticle',
            name='thumbnail',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='guidearticle',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='guidearticle',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
