# Generated by Django 5.2.6 on 2026-04-21 09:10

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0003_legalclause_slug_alter_legalclause_unique_together'),
        ('webshell', '0003_alter_guidearticle_options_remove_guidearticle_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Answer')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='webshell.faqcategory')),
                ('legal_clauses', models.ManyToManyField(blank=True, related_name='faq_items', to='knowledge_base.legalclause')),
            ],
        ),
    ]
