# Generated by Django 5.2.6 on 2026-02-25 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingRegime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LegalClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(blank=True, max_length=50)),
                ('article', models.CharField(max_length=50)),
                ('clause', models.CharField(blank=True, max_length=50)),
                ('point', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('content', models.TextField()),
                ('topic', models.CharField(blank=True, db_index=True, max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccountChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_code', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=255)),
                ('account_type', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='knowledge_base.accountchart')),
                ('regime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge_base.accountingregime')),
            ],
            options={
                'unique_together': {('regime', 'account_code')},
            },
        ),
        migrations.CreateModel(
            name='KnowledgeIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('text_content', models.TextField()),
                ('embedding', models.JSONField()),
                ('keywords', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='AccountingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('credit_accounts', models.ManyToManyField(related_name='credit_rules', to='knowledge_base.accountchart')),
                ('debit_accounts', models.ManyToManyField(related_name='debit_rules', to='knowledge_base.accountchart')),
                ('regime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge_base.accountingregime')),
                ('legal_clauses', models.ManyToManyField(blank=True, to='knowledge_base.legalclause')),
            ],
        ),
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('code', models.CharField(max_length=100)),
                ('document_type', models.CharField(choices=[('thong_tu', 'Thông tư'), ('nghi_dinh', 'Nghị định'), ('chuan_muc', 'Chuẩn mực'), ('luat', 'Luật')], max_length=50)),
                ('issued_date', models.DateField()),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('file', models.FileField(upload_to='knowledge/legal/raw/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='knowledge_base.legaldocument')),
            ],
        ),
        migrations.AddField(
            model_name='legalclause',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='knowledge_base.legaldocument'),
        ),
        migrations.AddIndex(
            model_name='legalclause',
            index=models.Index(fields=['topic'], name='knowledge_b_topic_98f891_idx'),
        ),
        migrations.AddIndex(
            model_name='legalclause',
            index=models.Index(fields=['article'], name='knowledge_b_article_80c80d_idx'),
        ),
    ]
