# Generated by Django 5.2.6 on 2026-04-16 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('legal_clauses', models.ManyToManyField(blank=True, related_name='related_sectors', to='knowledge_base.legalclause')),
            ],
        ),
        migrations.CreateModel(
            name='TaxPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('HKD_PLUS', 'HKD Thuế khoán % doanh thu'), ('HKD_PRO', 'HKD Kê khai khấu trừ')], max_length=20)),
                ('vat_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pit_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tax_formula', models.TextField(blank=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('legal_clauses', models.ManyToManyField(blank=True, related_name='tax_policies', to='knowledge_base.legalclause')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_policies', to='knowledge_base.businesssector')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
    ]
