# Generated by Django 5.2.6 on 2026-04-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0002_businesssector_taxpolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalclause',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='legalclause',
            unique_together={('document', 'article', 'clause', 'point')},
        ),
    ]
