# Generated by Django 5.2.6 on 2026-04-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0003_legalclause_slug_alter_legalclause_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalclause',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
