# Generated by Django 5.2.6 on 2026-03-12 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appconfig', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sidebarmenu',
            old_name='module',
            new_name='feature_module',
        ),
        migrations.AddField(
            model_name='sidebarmenu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='appconfig.sidebarmenu'),
        ),
    ]
