# Generated by Django 5.2.6 on 2026-02-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('group_name', models.CharField(max_length=255)),
                ('group_type', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('file_format', models.CharField(max_length=20)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('doc_type', models.CharField(blank=True, max_length=100, null=True)),
                ('doc_no', models.CharField(blank=True, max_length=100, null=True)),
                ('doc_date', models.DateField(blank=True, null=True)),
                ('tax_code', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('tax_rate', models.FloatField(blank=True, null=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('accounting_status', models.CharField(default='Chưa ghi sổ', max_length=50)),
                ('bookkeeping_date', models.DateField(blank=True, null=True)),
                ('accounting_code', models.CharField(blank=True, max_length=128, null=True)),
                ('drive_file_id', models.CharField(blank=True, max_length=255, null=True)),
                ('drive_path', models.CharField(blank=True, max_length=1024, null=True)),
                ('drive_mime', models.CharField(blank=True, max_length=100, null=True)),
                ('drive_link', models.URLField(blank=True, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('enable', 'Enable'), ('disabled', 'Disabled'), ('invalid', 'Invalid'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('ocr_text', models.TextField(blank=True, null=True)),
                ('extract_log', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Mã biểu mẫu theo quy định (VD: 01-TT, 02-VT, 01a-LĐTL...)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Tên đầy đủ của biểu mẫu (VD: Phiếu thu, Phiếu chi, Hóa đơn GTGT...)', max_length=255)),
                ('title', models.CharField(blank=True, help_text="Tiêu đề ngắn dùng để match mạnh (VD: 'PHIẾU THU')", max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Mô tả chi tiết nội dung, mục đích sử dụng biểu mẫu.', null=True)),
                ('regulation_source', models.CharField(blank=True, help_text='Nguồn quy định hoặc thông tư gốc (VD: Thông tư 200/2014/TT-BTC, TT133/2016...)', max_length=255, null=True)),
                ('version', models.CharField(blank=True, help_text='Phiên bản hoặc năm ban hành biểu mẫu.', max_length=50, null=True)),
                ('category', models.CharField(blank=True, help_text='Nhóm biểu mẫu (VD: Kế toán, Thuế, Lao động, Ngân hàng, ...)', max_length=100, null=True)),
                ('pdf_file', models.FileField(blank=True, help_text='File PDF của biểu mẫu gốc (chuẩn theo thông tư).', null=True, upload_to='documents/pdf/')),
                ('docx_file', models.FileField(blank=True, help_text='File DOCX của biểu mẫu (dùng để sinh chứng từ tự động).', null=True, upload_to='documents/docx/')),
                ('image_preview', models.ImageField(blank=True, help_text='Ảnh xem trước hoặc thumbnail của biểu mẫu.', null=True, upload_to='documents/image/')),
                ('structure_json', models.JSONField(blank=True, help_text='Cấu trúc dữ liệu ánh xạ các trường trên biểu mẫu, gồm vị trí, tên trường, regex nhận dạng, label, v.v.', null=True)),
                ('example_text', models.TextField(blank=True, help_text='Ví dụ text OCR của biểu mẫu (dùng để train).', null=True)),
                ('keywords', models.TextField(blank=True, help_text='Từ khóa (có dấu), cách nhau bởi dấu phẩy.', null=True)),
                ('code_norm', models.CharField(blank=True, db_index=True, max_length=80, null=True)),
                ('title_norm', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('keywords_norm', models.TextField(blank=True, null=True)),
                ('drive_group_path', models.CharField(blank=True, help_text="Tên nhóm folder lưu chứng từ trên Drive của mỗi user, VD: 'chung_tu_ke_toan/tien_mat' hoặc 'hoa_don/ban_ra'", max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Trạng thái hoạt động của mẫu.')),
                ('confidence_threshold', models.FloatField(default=0.3, help_text='Ngưỡng xác suất (0–1) để AI nhận diện mẫu này là khớp.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Biểu mẫu kế toán',
                'verbose_name_plural': 'Danh mục Biểu mẫu (Form Templates)',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='GroupDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('main', 'Chứng từ hạch toán'), ('support', 'Chứng từ bổ trợ')], default='support', max_length=20)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
