# Generated by Django 5.2.6 on 2026-02-25 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentgroup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentmetadata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Người tạo hoặc quản lý mẫu này.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userdrive'),
        ),
        migrations.AddField(
            model_name='groupdocument',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_groups', to='documents.documentmetadata'),
        ),
        migrations.AddField(
            model_name='groupdocument',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_documents', to='documents.documentgroup'),
        ),
        migrations.AlterUniqueTogether(
            name='groupdocument',
            unique_together={('group', 'document')},
        ),
    ]
