# Generated by Django 5.2.6 on 2026-03-05 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_code', models.CharField(choices=[('hkd', 'HKD'), ('hkd_plus', 'HKD Plus'), ('hkd_pro', 'HKD Pro')], max_length=50)),
                ('flow', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('form_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.formtemplate')),
            ],
            options={
                'unique_together': {('plan_code', 'flow')},
            },
        ),
    ]
