# Generated by Django 5.2.6 on 2026-04-13 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_registermapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formtemplate',
            name='regulation_source',
            field=models.CharField(blank=True, help_text='Nguồn quy định hoặc thông tư gốc (VD: 152/2025/TT-BTC, 99/2025/TT-BTC...)', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='AccountingBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('plan', models.CharField(choices=[('hkd', 'Hộ kinh doanh'), ('hkd_plus', 'HKD Plus'), ('hkd_pro', 'HKD Pro'), ('enterprise', 'Doanh nghiệp')], max_length=20)),
                ('regulation', models.CharField(help_text='Thông tư áp dụng', max_length=100)),
                ('book_type', models.CharField(choices=[('general', 'Sổ tổng hợp'), ('detail', 'Sổ chi tiết'), ('journal', 'Nhật ký'), ('report', 'Báo cáo')], max_length=20)),
                ('doc_register', models.CharField(max_length=100)),
                ('account_codes', models.JSONField(blank=True, null=True)),
                ('filter_conditions', models.JSONField(blank=True, null=True)),
                ('period_type', models.CharField(choices=[('month', 'Tháng'), ('quarter', 'Quý'), ('year', 'Năm')], default='month', max_length=20)),
                ('display_order', models.IntegerField(default=0)),
                ('is_default', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_books', to='documents.accountingbook')),
                ('templates', models.ManyToManyField(blank=True, to='documents.formtemplate')),
            ],
        ),
    ]
