# Generated by Django 5.2.6 on 2026-03-04 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('effective_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('level', models.PositiveSmallIntegerField()),
                ('account_type', models.CharField(choices=[('asset', 'Tài sản'), ('liability', 'Nợ phải trả'), ('equity', 'Vốn chủ sở hữu'), ('revenue', 'Doanh thu'), ('expense', 'Chi phí')], max_length=20)),
                ('normal_balance', models.CharField(choices=[('debit', 'Dư Nợ'), ('credit', 'Dư Có')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounting.account')),
                ('regulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='accounting.regulation')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('regulation', 'code')},
            },
        ),
    ]
