# Generated by Django 5.2.6 on 2026-03-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_account_level_alter_account_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='normal_balance',
            field=models.CharField(blank=True, choices=[('debit', 'Dư Nợ'), ('credit', 'Dư Có')], max_length=10, null=True),
        ),
    ]
