# Generated by Django 5.2.6 on 2026-03-04 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_account_normal_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('asset', 'Tài sản'), ('liability', 'Nợ phải trả'), ('equity', 'Vốn chủ sở hữu'), ('revenue', 'Doanh thu'), ('expense', 'Chi phí'), ('income_other', 'Thu nhập khác'), ('expense_other', 'Chi phí khác'), ('result', 'Xác định kết quả')], max_length=20),
        ),
    ]
